[dev]
  framework = "#custom"
  command = "expo start"
  targetPort = 19000

[build]
  command = "expo build:web"
  publish = "web-build"
  functions = "functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200